Fix probe to avoid false negatives
appgate/sdp-k8s-injector pull request #188
Opened 2023-09-22 11:13 UTC by lepiolet

## Description

## Checklist
- [ ] Bump `.version` and `.appVersion` in [k8s/crd/Chart.yaml](../k8s/crd/Chart.yaml)
- [ ] Bump `.version` and `.appVersion` in [k8s/chart/Chart.yaml](../k8s/chart/Chart.yaml)

2023-09-22 11:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/appgate/sdp-k8s-injector?pullRequest=188) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/appgate/sdp-k8s-injector?pullRequest=188) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/appgate/sdp-k8s-injector?pullRequest=188) it.</sub>

2023-09-22 12:05 UTC, thomascellerier requested changes
Looks good except for the typo.

2023-09-22 12:05 UTC, thomascellerier commented on assets/sdp-service-probe
> +#!/usr/bin/env/sh
Typo here:
```suggestion
#!/usr/bin/env sh
```

2023-09-22 12:11 UTC, thomascellerier approved these changes

2023-10-04 13:43 UTC, mandopaloooza commented
Rebasing PR.

2023-10-04 13:53 UTC, mandopaloooza approved these changes

2023-10-04 13:53 UTC, merged